// Riot public queue catalog and local client /lol-game-queues/v1/queues, 2026-09-14.
// Historical entries describe importable queues, not current matchmaking availability.
export const QUEUE_CATALOG = [
  {
    id: 0,
    label: "Personalizada",
    mode: "",
    group: "Principales",
  },
  {
    id: 2,
    label: "5v5 Blind Pick games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 4,
    label: "5v5 Ranked Solo games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 6,
    label: "5v5 Ranked Premade games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 7,
    label: "Co-op vs AI games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 8,
    label: "3v3 Normal games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 9,
    label: "3v3 Ranked Flex games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 14,
    label: "5v5 Draft Pick games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 16,
    label: "5v5 Dominion Blind Pick games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 17,
    label: "5v5 Dominion Draft Pick games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 25,
    label: "Dominion Co-op vs AI games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 31,
    label: "Co-op vs AI Intro Bot games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 32,
    label: "Co-op vs AI Beginner Bot games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 33,
    label: "Co-op vs AI Intermediate Bot games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 41,
    label: "3v3 Ranked Team games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 42,
    label: "5v5 Ranked Team games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 52,
    label: "Co-op vs AI games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 61,
    label: "5v5 Team Builder games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 65,
    label: "5v5 ARAM games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 67,
    label: "ARAM Co-op vs AI games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 70,
    label: "One for All games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 72,
    label: "1v1 Snowdown Showdown games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 73,
    label: "2v2 Snowdown Showdown games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 75,
    label: "6v6 Hexakill games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 76,
    label: "Ultra Rapid Fire games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 78,
    label: "One For All: Mirror Mode games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 83,
    label: "Co-op vs AI Ultra Rapid Fire games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 91,
    label: "Doom Bots Rank 1 games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 92,
    label: "Doom Bots Rank 2 games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 93,
    label: "Doom Bots Rank 5 games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 96,
    label: "Ascension games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 98,
    label: "6v6 Hexakill games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 100,
    label: "5v5 ARAM games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 300,
    label: "Legend of the Poro King games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 310,
    label: "Nemesis games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 313,
    label: "Black Market Brawlers games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 315,
    label: "Nexus Siege games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 317,
    label: "Definitely Not Dominion games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 318,
    label: "ARURF games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 325,
    label: "All Random games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 400,
    label: "Normal · Reclutamiento",
    mode: "CLASSIC",
    group: "Principales",
  },
  {
    id: 410,
    label: "5v5 Ranked Dynamic games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 420,
    label: "Clasificatoria · Solo/Dúo",
    mode: "CLASSIC",
    group: "Principales",
  },
  {
    id: 430,
    label: "Normal · A ciegas",
    mode: "CLASSIC",
    group: "Principales",
  },
  {
    id: 440,
    label: "Clasificatoria · Flexible",
    mode: "CLASSIC",
    group: "Principales",
  },
  {
    id: 450,
    label: "ARAM normal",
    mode: "ARAM",
    group: "Principales",
  },
  {
    id: 460,
    label: "3v3 Blind Pick games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 470,
    label: "3v3 Ranked Flex games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 480,
    label: "Modo rápido · Swiftplay",
    mode: "SWIFTPLAY",
    group: "Principales",
  },
  {
    id: 490,
    label: "Partida rápida · Quickplay",
    mode: "CLASSIC",
    group: "Principales",
  },
  {
    id: 600,
    label: "Blood Hunt Assassin games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 610,
    label: "Dark Star: Singularity games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 700,
    label: "Clash · Grieta",
    mode: "CLASSIC",
    group: "Principales",
  },
  {
    id: 701,
    label: "Clash",
    mode: "CLASSIC",
    group: "Otros modos",
  },
  {
    id: 710,
    label: "Clasificatoria de 5",
    mode: "CLASSIC",
    group: "Otros modos",
  },
  {
    id: 720,
    label: "Clash · ARAM",
    mode: "ARAM",
    group: "Principales",
  },
  {
    id: 721,
    label: "Clash",
    mode: "ARAM",
    group: "Otros modos",
  },
  {
    id: 740,
    label: "Clash de URF (todo aleatorio)",
    mode: "URF",
    group: "Otros modos",
  },
  {
    id: 741,
    label: "Clash de URF (todo aleatorio)",
    mode: "URF",
    group: "Otros modos",
  },
  {
    id: 800,
    label: "Co-op vs. AI Intermediate Bot games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 810,
    label: "Co-op vs. AI Intro Bot games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 820,
    label: "Co-op vs. AI Beginner Bot games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 830,
    label: "Introducción",
    mode: "CLASSIC",
    group: "Cooperativo y bots",
  },
  {
    id: 840,
    label: "Principiante",
    mode: "CLASSIC",
    group: "Cooperativo y bots",
  },
  {
    id: 843,
    label: "Cola 843",
    mode: "SWIFTPLAY",
    group: "Cooperativo y bots",
  },
  {
    id: 850,
    label: "Intermedia",
    mode: "CLASSIC",
    group: "Cooperativo y bots",
  },
  {
    id: 860,
    label: "ARAM 5v5 Bots",
    mode: "ARAM",
    group: "Cooperativo y bots",
  },
  {
    id: 870,
    label: "Introducción",
    mode: "SWIFTPLAY",
    group: "Cooperativo y bots",
  },
  {
    id: 880,
    label: "Principiante",
    mode: "SWIFTPLAY",
    group: "Cooperativo y bots",
  },
  {
    id: 890,
    label: "Intermedio",
    mode: "SWIFTPLAY",
    group: "Cooperativo y bots",
  },
  {
    id: 900,
    label: "URF (todo aleatorio)",
    mode: "URF",
    group: "Otros modos",
  },
  {
    id: 901,
    label: "Prueba: ARURF 1v1",
    mode: "URF",
    group: "Otros modos",
  },
  {
    id: 910,
    label: "Ascension games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 920,
    label: "Legend of the Poro King games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 940,
    label: "Nexus Siege games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 950,
    label: "Doom Bots Voting games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 960,
    label: "Doom Bots Standard games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 980,
    label: "Star Guardian Invasion: Normal games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 990,
    label: "Star Guardian Invasion: Onslaught games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1000,
    label: "PROJECT: Hunters games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1010,
    label: "Snow ARURF games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1020,
    label: "Uno para Todos",
    mode: "ONEFORALL",
    group: "Otros modos",
  },
  {
    id: 1030,
    label: "Odyssey Extraction: Intro games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1040,
    label: "Odyssey Extraction: Cadet games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1050,
    label: "Odyssey Extraction: Crewmember games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1060,
    label: "Odyssey Extraction: Captain games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1070,
    label: "Odyssey Extraction: Onslaught games",
    mode: "",
    group: "Otros modos",
  },
  {
    id: 1200,
    label: "Nexus Blitz games",
    mode: "",
    group: "Históricas",
  },
  {
    id: 1300,
    label: "Bombardeo al Nexo",
    mode: "NEXUSBLITZ",
    group: "Otros modos",
  },
  {
    id: 1400,
    label: "Libro de Hechizos Definitivos",
    mode: "ULTBOOK",
    group: "Otros modos",
  },
  {
    id: 1700,
    label: "Arena",
    mode: "CHERRY",
    group: "Principales",
  },
  {
    id: 1704,
    label: "Arena (2v2 beta pública)",
    mode: "CHERRY",
    group: "Otros modos",
  },
  {
    id: 1710,
    label: "Arena · Normal",
    mode: "CHERRY",
    group: "Principales",
  },
  {
    id: 1740,
    label: "Arena con Valentía",
    mode: "CHERRY",
    group: "Otros modos",
  },
  {
    id: 1750,
    label: "Arena 3x6",
    mode: "CHERRY",
    group: "Otros modos",
  },
  {
    id: 1810,
    label: "Enjambre",
    mode: "STRAWBERRY",
    group: "Otros modos",
  },
  {
    id: 1820,
    label: "Enjambre",
    mode: "STRAWBERRY",
    group: "Otros modos",
  },
  {
    id: 1830,
    label: "Enjambre",
    mode: "STRAWBERRY",
    group: "Otros modos",
  },
  {
    id: 1840,
    label: "Enjambre",
    mode: "STRAWBERRY",
    group: "Otros modos",
  },
  {
    id: 1900,
    label: "Ultra Rapid Fire",
    mode: "URF",
    group: "Otros modos",
  },
  {
    id: 2000,
    label: "Parte 1 del tutorial",
    mode: "TUTORIAL_MODULE_1",
    group: "Otros modos",
  },
  {
    id: 2010,
    label: "Parte 2 del tutorial",
    mode: "TUTORIAL_MODULE_2",
    group: "Otros modos",
  },
  {
    id: 2020,
    label: "Parte 3 del tutorial",
    mode: "TUTORIAL_MODULE_3",
    group: "Otros modos",
  },
  {
    id: 2300,
    label: "Trifulca",
    mode: "BRAWL",
    group: "Otros modos",
  },
  {
    id: 2400,
    label: "ARAM Caos",
    mode: "KIWI",
    group: "Principales",
  },
  {
    id: 2410,
    label: "Torneo de ARAM: Caos",
    mode: "KIWI",
    group: "Otros modos",
  },
  {
    id: 2450,
    label: "ARAM Caos Classic",
    mode: "KIWI_JADE",
    group: "Principales",
  },
  {
    id: 3100,
    label: "Grieta del Invocador - A ciegas y personalizada",
    mode: "CLASSIC",
    group: "Personalizadas",
  },
  {
    id: 3110,
    label: "Grieta del Invocador - Reclutamiento y personalizada",
    mode: "CLASSIC",
    group: "Personalizadas",
  },
  {
    id: 3120,
    label: "Grieta del Invocador - Todo aleatorio",
    mode: "CLASSIC",
    group: "Personalizadas",
  },
  {
    id: 3130,
    label: "Grieta del Invocador - Torneo de reclutamiento",
    mode: "CLASSIC",
    group: "Personalizadas",
  },
  {
    id: 3140,
    label: "Herramienta de práctica multijugador personalizada",
    mode: "PRACTICETOOL",
    group: "Personalizadas",
  },
  {
    id: 3150,
    label: "Cola 3150",
    mode: "URF",
    group: "Personalizadas",
  },
  {
    id: 3161,
    label: "Cola 3161",
    mode: "CLASSIC",
    group: "Personalizadas",
  },
  {
    id: 3200,
    label: "Abismo de los Lamentos - A ciegas y personalizada",
    mode: "ARAM",
    group: "Personalizadas",
  },
  {
    id: 3210,
    label: "Abismo de los Lamentos - Reclutamiento y personalizada",
    mode: "ARAM",
    group: "Personalizadas",
  },
  {
    id: 3220,
    label: "Abismo de los Lamentos - Todo aleatorio",
    mode: "ARAM",
    group: "Personalizadas",
  },
  {
    id: 3230,
    label: "Abismo de los Lamentos - Torneo de reclutamiento y personalizada",
    mode: "ARAM",
    group: "Personalizadas",
  },
  {
    id: 3260,
    label: "Grieta Classic",
    mode: "JADE",
    group: "Personalizadas",
  },
  {
    id: 3262,
    label: "Grieta Classic",
    mode: "JADE",
    group: "Personalizadas",
  },
  {
    id: 3270,
    label: "ARAM: Caos",
    mode: "KIWI",
    group: "Personalizadas",
  },
  {
    id: 3280,
    label: "ARAM: Caos tipo Classic",
    mode: "KIWI_JADE",
    group: "Personalizadas",
  },
  {
    id: 4210,
    label: "Bots Malditos",
    mode: "RUBY",
    group: "Otros modos",
  },
  {
    id: 4220,
    label: "Bots Malditos: Difícil",
    mode: "RUBY",
    group: "Otros modos",
  },
  {
    id: 4240,
    label: "BOTS MALDITOS: ¡LA MALDICIÓN DE VEIGAR!",
    mode: "RUBY_TRIAL_1",
    group: "Otros modos",
  },
  {
    id: 4250,
    label: "BOTS MALDITOS: ¡LA MALDAD DE VEIGAR!",
    mode: "RUBY_TRIAL_2",
    group: "Otros modos",
  },
  {
    id: 4260,
    label: "BOTS MALDITOS: ¡LA LETALIDAD DE VEIGAR!",
    mode: "RUBY_TRIAL_3",
    group: "Otros modos",
  },
  {
    id: 4310,
    label: "5v5 - Classic",
    mode: "JADE",
    group: "Otros modos",
  },
  {
    id: 4320,
    label: "Jade",
    mode: "JADE",
    group: "Otros modos",
  },
];
